/**
 * a11oy-ks18-witness.ts — Kochen–Specker 18-vector contextuality witness
 * Organ: a11oy (BRAIN / GOVERNANCE CORTEX)
 *
 * STATUS: TUTORIAL FIXTURE — runnable copy for the recipe smoke tests.
 *   The CANONICAL implementation is:
 *     a11oy/web/packages/a11oy-core/src/quantum/kochen_specker_18.ts
 *
 * Source: Cabello, A., Estebaranz, J. M., & García-Alcaine, G. (1996).
 *   "Bell-Kochen-Specker theorem: A proof with 18 vectors."
 *   Physics Letters A 212(4), 183–187. arXiv:quant-ph/9706009.
 *
 * Related: Peres, A. (1991). "Two simple proofs of the Kochen-Specker
 *   theorem." J. Phys. A: Math. Gen. 24, L175. — established the 24-ray
 *   parent construction in ℝ⁴ from which our 18 rays are drawn.
 *
 * Structure: 18 rays in ℝ⁴ (entries in {-1, 0, +1}) arranged into 9
 * contexts. Each context is a set of 4 mutually orthogonal vectors,
 * forming a basis of ℝ⁴. Every ray belongs to exactly 2 of the 9
 * contexts. The 9 contexts × 4 vectors = 36 cells = 18 vectors × 2
 * incidences (combinatorial parity).
 *
 * Soundness — the KS theorem (NCHV impossibility):
 *   THEOREM: No function f: {18 vectors} → {0, 1} can satisfy
 *   "exactly one '1' per context" for all 9 contexts.
 *   PROOF: Counting "1"s over the 9 contexts yields 9 (one per context,
 *   by NCHV assumption); but each vector appears in 2 contexts, so the
 *   same count equals 2 · Σᵥ f(v), which is even. 9 is odd. ∎
 *   This is the parity argument of Cabello et al. (1996).
 *
 * Governance use: the agent answers a sequence of dichotomous policy
 * probes drawn from the 18 vectors. If the rolling response distribution
 * admits a non-contextual hidden-variable (NCHV) assignment — i.e., the
 * responses are compressible to a single classical function f: vectors
 * → {0, 1} that satisfies every context constraint observed — then the
 * agent has collapsed into a classical lookup table (flag = CLASSICAL).
 * Otherwise the responses are genuinely context-dependent and the agent
 * passes the contextuality witness (flag in BOHR_NORMAL / ELEVATED /
 * ANOMALOUS, indexed by the inconsistency fraction).
 *
 * The 18 vectors and 9 contexts below were generated by exhaustive
 * search over the Peres 1991 24-ray set in ℝ⁴ (canonical {-1, 0, +1}^4
 * representatives) for a 9-context cover with every ray appearing in
 * exactly 2 contexts; uniqueness up to symmetry of the chosen set is a
 * standard combinatorial fact about Cabello-class KS-18 structures.
 * Verified by `verifyKSStructure()`.
 */

export interface KSObservation {
  contextId: string;
  vectorIdx: number;  // 0..17
  response: 0 | 1;
}

export interface KSWitnessResult {
  contextualityFraction: number;
  isNCHVConsistent: boolean;
  anomalyFlag: "CLASSICAL" | "BOHR_NORMAL" | "BOHR_ELEVATED" | "BOHR_ANOMALOUS";
  totalObservations: number;
  inconsistencies: number;
  contextsChecked: number;
}

/**
 * The 18 KS vectors in ℝ⁴ — unnormalised, entries in {-1, 0, +1}.
 * Cabello et al. 1996 / Peres 1991. Verified orthogonal in each context.
 */
export const KS18_VECTORS: ReadonlyArray<readonly [number, number, number, number]> = [
  [ 1,  0,  0,  0], //  0
  [ 0,  1,  0,  0], //  1
  [ 0,  0,  1,  0], //  2
  [ 1,  1,  0,  0], //  3
  [ 1,  0,  1,  0], //  4
  [ 1,  0,  0,  1], //  5
  [ 1,  0,  0, -1], //  6
  [ 0,  1,  1,  0], //  7
  [ 0,  1,  0,  1], //  8
  [ 0,  1,  0, -1], //  9
  [ 0,  0,  1,  1], // 10
  [ 0,  0,  1, -1], // 11
  [ 1,  1, -1,  1], // 12
  [ 1,  1, -1, -1], // 13
  [ 1, -1,  1,  1], // 14
  [ 1, -1,  1, -1], // 15
  [ 1, -1, -1,  1], // 16
  [ 1, -1, -1, -1], // 17
] as const;

/**
 * The 9 contexts: each a tuple of 4 mutually-orthogonal vectors (a
 * basis of ℝ⁴), every vector appearing in exactly 2 contexts.
 */
export const KS18_CONTEXTS: ReadonlyArray<readonly [number, number, number, number]> = [
  [ 0,  1, 10, 11],
  [ 0,  2,  8,  9],
  [ 1,  2,  5,  6],
  [ 3, 10, 15, 16],
  [ 3, 11, 14, 17],
  [ 4,  8, 13, 16],
  [ 4,  9, 12, 17],
  [ 5,  7, 13, 15],
  [ 6,  7, 12, 14],
] as const;

/**
 * Verify the KS-18 structural invariants:
 *   (i)  every context's 4 vectors are pairwise orthogonal,
 *   (ii) every vector appears in exactly 2 contexts.
 * These two facts drive Cabello's parity proof of the KS theorem.
 */
export function verifyKSStructure(): { ok: boolean; reason?: string } {
  const dot = (a: readonly number[], b: readonly number[]) =>
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3];

  for (let c = 0; c < KS18_CONTEXTS.length; c++) {
    const ctx = KS18_CONTEXTS[c];
    for (let i = 0; i < 4; i++) {
      for (let j = i + 1; j < 4; j++) {
        const d = dot(KS18_VECTORS[ctx[i]], KS18_VECTORS[ctx[j]]);
        if (d !== 0) {
          return { ok: false, reason: `Context ${c}: vectors ${ctx[i]}, ${ctx[j]} not orthogonal (dot=${d})` };
        }
      }
    }
  }
  const occur = new Array<number>(18).fill(0);
  for (const ctx of KS18_CONTEXTS) for (const v of ctx) occur[v]++;
  for (let v = 0; v < 18; v++) {
    if (occur[v] !== 2) {
      return { ok: false, reason: `Vector ${v} appears in ${occur[v]} contexts (expected 2)` };
    }
  }
  if (KS18_CONTEXTS.length !== 9) {
    return { ok: false, reason: `Got ${KS18_CONTEXTS.length} contexts (expected 9)` };
  }
  return { ok: true };
}

export class KochenSpecker18Witness {
  private observations: KSObservation[] = [];
  private windowSize: number;

  constructor(windowSize = 100) { this.windowSize = windowSize; }

  record(obs: KSObservation): void {
    this.observations.push(obs);
    if (this.observations.length > this.windowSize) this.observations.shift();
  }

  evaluate(): KSWitnessResult {
    const responseMap = new Map<number, 0 | 1>();
    for (const obs of this.observations) responseMap.set(obs.vectorIdx, obs.response);

    let inconsistencies = 0;
    let contextsChecked = 0;

    for (const ctx of KS18_CONTEXTS) {
      const vals = ctx.map(i => responseMap.get(i));
      if (vals.every(v => v !== undefined)) {
        contextsChecked++;
        // NCHV constraint: in each orthogonal 4-basis, exactly one
        // projector reads "1" (assigned the value true).
        const ones = (vals as Array<0 | 1>).reduce<number>((a, b) => a + b, 0);
        if (ones !== 1) inconsistencies++;
      }
    }

    const cf = contextsChecked > 0 ? inconsistencies / contextsChecked : 0;
    const flag: KSWitnessResult["anomalyFlag"] =
      cf === 0 ? "CLASSICAL"
      : cf <= 0.3 ? "BOHR_NORMAL"
      : cf <= 0.6 ? "BOHR_ELEVATED"
      : "BOHR_ANOMALOUS";

    return {
      contextualityFraction: cf,
      isNCHVConsistent: inconsistencies === 0,
      anomalyFlag: flag,
      totalObservations: this.observations.length,
      inconsistencies,
      contextsChecked,
    };
  }
}
